sonar.projectKey=izzathulmardhiyah274_testing2
sonar.organization=izzathulmardhiyah274

sonar.sources=app,resources/routes
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8